DATA:
  DATA_NAME: 'THUMOS'
  DATA_INFO: 'data/data_info.json'
  DATA_ROOT: 'data/THUMOS'
INPUT:
  MODALITY: 'twostream'
  VISUAL_FEATURE: 'rgb_kinetics_resnet50'
  MOTION_FEATURE: 'flow_kinetics_bninception'
  OBJECT_FEATURE: 'flow_kinetics_bninception'
MODEL:
  MODEL_NAME: 'CMeRT'
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 1024
  LSTR:
    NUM_HEADS: 8
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.0
    ACTIVATION: 'relu'
    LONG_MEMORY_SECONDS: 256
    LONG_MEMORY_SAMPLE_RATE: 4
    LONG_MEMORY_USE_PE: False
    LONG_MEMORY_INCLUDE_WORK: True
    WORK_MEMORY_SECONDS: 4
    WORK_MEMORY_SAMPLE_RATE: 1
    CONTEXT_SECONDS: 0.5
    CONTEXT_MEMORY_SAMPLE_RATE: 1
    FUTURE_SECONDS: 12
    FUTURE_SAMPLE_RATE: 1
    ANTICIPATION_SECONDS: 2
    REFINE_TIMES: 1
    ENC_MODULE: [[16, 1, True], [32, 2, True]] #
    DEC_MODULE: [-1, 2, True]
    GEN_MODULE: [ 32, 2, True ]
    FUT_MODULE: [[ 48, 1, True ],]
  CRITERIONS: [['MCE', {}]]
  PP_SIZE: 5
DATA_LOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  PIN_MEMORY: True
  TYPE: ''
SOLVER:
  NUM_EPOCHS: 16
  OPTIMIZER: 'adam'
  BASE_LR: 2e-04
  WEIGHT_DECAY: 5e-05
  SAVE_EVERY: 1
  S1_W: 0.1
  S2_W: 1.0
  F_W: 0.5
  SCHEDULER:
    SCHEDULER_NAME: 'warmup_cosine'
    WARMUP_FACTOR: 0.3
    WARMUP_EPOCHS: 10.0
    WARMUP_METHOD: 'linear'
